In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
fraud = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv")
fraud.head()

distance_from_home  distance_from_last_transaction  \
0           57.877857                        0.311140   
1           10.829943                        0.175592   
2            5.091079                        0.805153   
3            2.247564                        5.600044   
4           44.190936                        0.566486   

   ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                        1.945940              1.0        1.0   
1                        1.294219              1.0        0.0   
2                        0.427715              1.0        0.0   
3                        0.362663              1.0        1.0   
4                        2.222767              1.0        1.0   

   used_pin_number  online_order  fraud  
0              0.0           0.0    0.0  
1              0.0           0.0    0.0  
2              0.0           1.0    0.0  
3              0.0           1.0    0.0  
4              0.0           1.0    0.0

In [11]:
print(fraud['fraud'].value_counts())
# target variable (fraud times) only occupy less than 10% of total samples , so yes we are dealing with an imbalanced dataset

fraud
0.0    912597
1.0     87403
Name: count, dtype: int64


In [41]:
# train model
X = fraud.drop(columns=['fraud'])
y = fraud['fraud']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.3,random_state=42)
model = LogisticRegression()
model.fit(X_train,y_train)

# 3 evaluate model
y_pred = model.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
# f1-score for 1.0(positive) only 0.71 means this model performed poor in predicing minority (positive) class

4 
ros = RandomOverSampler(random_state=42)
X_resampled,y_resampled = ros.fit_resample(X_train,y_train)
model.fit(X_resampled,y_resampled)

y_pred_resampled = model.predict(X_test)
print(confusion_matrix(y_test,y_pred_resampled))
print(classification_report(y_test,y_pred_resampled))
# After Oversample, f1-score drop 2% for Negative(0.0) and f1-score go up 2% for Positive(1.0) 
# so hardly to conclude such oversample did improve the performance of our model

# 5
rus = RandomUnderSampler(random_state=42)
X_resampled2,y_resampled2 = rus.fit_resample(X_train,y_train)
model.fit(X_resampled2,y_resampled2)

y_pred_resampled2 = model.predict(X_test)
print(confusion_matrix(y_test,y_pred_resampled2))
print(classification_report(y_test,y_pred_resampled2))
# # After Undersample, compare with orignal result :f1-score drop 2% for Negative(0.0) and f1-score kept same for Positive(1.0) 
# # so here we conclude such Undersample did decrease the performance of our model

# 6
smote = SMOTE(random_state=42)
X_resampled3,y_resampled3 = smote.fit_resample(X_train,y_train)
model.fit(X_resampled3,y_resampled3)

y_pred_resampled3 = model.predict(X_test)
print(confusion_matrix(y_test,y_pred_resampled3))
print(classification_report(y_test,y_pred_resampled3))
# After SMOTE, compare with orignal result :f1-score drop 2% for Negative(0.0) and f1-score increased 1% for Positive(1.0) 
# so here we conclude such SMOTEsample almost not improve the performance of our model

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[271913   1958]
 [ 10502  15627]]
              precision    recall  f1-score   support

         0.0       0.96      0.99      0.98    273871
         1.0       0.89      0.60      0.71     26129

    accuracy                           0.96    300000
   macro avg       0.93      0.80      0.85    300000
weighted avg       0.96      0.96      0.95    300000



C:\Users\dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[256615  17256]
 [  1399  24730]]
              precision    recall  f1-score   support

         0.0       0.99      0.94      0.96    273871
         1.0       0.59      0.95      0.73     26129

    accuracy                           0.94    300000
   macro avg       0.79      0.94      0.85    300000
weighted avg       0.96      0.94      0.94    300000



C:\Users\dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[255177  18694]
 [  1211  24918]]
              precision    recall  f1-score   support

         0.0       1.00      0.93      0.96    273871
         1.0       0.57      0.95      0.71     26129

    accuracy                           0.93    300000
   macro avg       0.78      0.94      0.84    300000
weighted avg       0.96      0.93      0.94    300000



C:\Users\dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[255897  17974]
 [  1333  24796]]
              precision    recall  f1-score   support

         0.0       0.99      0.93      0.96    273871
         1.0       0.58      0.95      0.72     26129

    accuracy                           0.94    300000
   macro avg       0.79      0.94      0.84    300000
weighted avg       0.96      0.94      0.94    300000

